
version: 1.0.{build}

#environment:
#  matrix:
#  - v: 1
#  - v: 2
#  - v: 3
#  - v: 4
#  - v: 5

image: Visual Studio 2017 RC

configuration: Release

platform: Any CPU

before_build:
- ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe', "C:\Tools\NuGet3\NuGet.exe")
- cmd: nuget restore

build:
  project: Rair.Utilities.Windows.sln
  verbosity: minimal

test:
  assemblies:
    - '**\*.tests.dll'
