version: 1.0.{build}

#environment:
#  matrix:
#  - v: 1
#  - v: 2
#  - v: 3
#  - v: 4
#  - v: 5

#image: Visual Studio 2017 RC

configuration: Release

platform: Any CPU

before_build:
- cmd: nuget restore

build:
  project: Rair.Utilities.Windows.sln
  verbosity: minimal

test:
  assemblies:
    - '**\*.tests.dll'
